// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAedO3RNSPvw4ihWzbHt7LDssXaaZTGmNY',
    appId: '1:982108295175:web:d4777899052f5f2a315aa2',
    messagingSenderId: '982108295175',
    projectId: 'codeapp-351a0',
    authDomain: 'codeapp-351a0.firebaseapp.com',
    storageBucket: 'codeapp-351a0.appspot.com',
    measurementId: 'G-K2BB5J69SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHvkDyLD9GmWRsie9TgigdJVBm3bS7ZqM',
    appId: '1:982108295175:android:af5fa43fb1cdc910315aa2',
    messagingSenderId: '982108295175',
    projectId: 'codeapp-351a0',
    storageBucket: 'codeapp-351a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDHcMCyL6vBhxWdd32-TTfB8eLzRMFw2c',
    appId: '1:982108295175:ios:27293844d9607f70315aa2',
    messagingSenderId: '982108295175',
    projectId: 'codeapp-351a0',
    storageBucket: 'codeapp-351a0.appspot.com',
    iosBundleId: 'com.example.mycodesaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDHcMCyL6vBhxWdd32-TTfB8eLzRMFw2c',
    appId: '1:982108295175:ios:27293844d9607f70315aa2',
    messagingSenderId: '982108295175',
    projectId: 'codeapp-351a0',
    storageBucket: 'codeapp-351a0.appspot.com',
    iosBundleId: 'com.example.mycodesaver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAedO3RNSPvw4ihWzbHt7LDssXaaZTGmNY',
    appId: '1:982108295175:web:c67f62512b784e0e315aa2',
    messagingSenderId: '982108295175',
    projectId: 'codeapp-351a0',
    authDomain: 'codeapp-351a0.firebaseapp.com',
    storageBucket: 'codeapp-351a0.appspot.com',
    measurementId: 'G-5ZPHGM9WC5',
  );
}
